In [ ]:
#pip install xlrd

In [ ]:
import pandas as pd
import csv

In [ ]:
# shows us what were working with
url = "https://www.sharkattackfile.net/spreadsheets/GSAF5.xls"
shark_data =  pd.read_excel(url)  # usecols=["Embarked"]
shark_data.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,15 Mar 2024,2024.0,Unprovoked,AUSTRALIA,Queensland,Bargara Beach,Swimming,Brooklyn Sauer,F,13,...,Tiger shark,"Yahoo News, 3/15/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04 Mar 2024,2024.0,Unprovoked,USA,Hawaii,"Old Man's, Waikiki",Surfing,Matthew White,M,NaN,...,Tiger shark 8',"Surfer, 3/6/2024F",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,02 Mar-2024,2024.0,Unprovoked,USA,Hawaii,"Rainbows, Oahu",Swimming,NaN,F,11,...,3' to 4' shark,"Hawaii News Now, 3/4/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25 Feb-2024,2024.0,Unprovoked,AUSTRALIA,Western Australia,"Sandlnd Island, Jurian Bay",NaN,female,F,46,...,Tiger shark,"WA Today, 2/26/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,14 Feb-2024,2024.0,Unprovoked,INDIA,Maharashtra,"Vaitarna River, Palghar District",Fishing,Vicky Suresh Govari,M,32,...,"Bull shark, 7'","Times of India, 2/14/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# replace all sentence and whitespace from the string date before handling to season
shark_data['Date'] = shark_data['Date'].replace('Before ', '', regex=True)
shark_data['Date'] = shark_data['Date'].replace(' ', '-', regex=True)
# Extract all months ans year from the columns date
shark_data['Month'] = shark_data['Date'].str.extract(r'([a-zA-Z]+)')
shark_data['Year']= shark_data['Date'].str.extract(r'(\d{4})')
# Create a Category for all months
def map_month(month_abbr):
    month_abbr_to_full = {
        'Jan': 'January', 'Feb': 'February', 'Mar': 'March', 'Apr': 'April',
        'May': 'May', 'Jun': 'June', 'Jul': 'July', 'Aug': 'August',
        'Sep': 'September', 'Oct': 'October', 'Nov': 'November', 'Dec': 'December'
    }
    return month_abbr_to_full.get(month_abbr, 'Unknown')
def get_season(month):
    if month in ['December', 'January', 'February']:
        return 'Winter'
    elif month in ['March', 'April', 'May']:
        return 'Spring'
    elif month in ['June', 'July', 'August']:
        return 'Summer'
    elif month in ['September', 'October', 'November']:
        return 'Fall'
    else:
        return 'Unknown'
shark_data['Month'] = shark_data['Month'].apply(map_month)
# Finish the category seasson for the months
shark_data['Season'] = shark_data['Month'].apply(get_season)

In [ ]:
shark_data

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22,Month,Season
0,15-Mar-2024,2024,Unprovoked,AUSTRALIA,Queensland,Bargara Beach,Swimming,Brooklyn Sauer,F,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,March,Spring
1,04-Mar-2024,2024,Unprovoked,USA,Hawaii,"Old Man's, Waikiki",Surfing,Matthew White,M,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,March,Spring
2,02-Mar-2024,2024,Unprovoked,USA,Hawaii,"Rainbows, Oahu",Swimming,NaN,F,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,March,Spring
3,25-Feb-2024,2024,Unprovoked,AUSTRALIA,Western Australia,"Sandlnd Island, Jurian Bay",NaN,female,F,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,February,Winter
4,14-Feb-2024,2024,Unprovoked,INDIA,Maharashtra,"Vaitarna River, Palghar District",Fishing,Vicky Suresh Govari,M,32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,February,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Unknown
6965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Unknown
6966,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Unknown
6967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Unknown
6968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Unknown

In [ ]:
url = "https://marineprotectedareas.noaa.gov/media/data/NOAA_Marine_Protected_Areas_Inventory_2023.xlsx"
usa_shark_data =  pd.read_excel(url)  # usecols=["Embarked"]
usa_shark_data.head()

,FID,OBJECTID,Site ID,Site Name,Level of Government,State,Level of Protection,Management Agency,Management Plan,Primary Conservation Focus,...,Marine Area (km2),Percent Area Marine,No-Take Area (km2),Longitude,Latitude,VxCount,SHAPE_Leng,SHAPE_Area,Shape__Area,Shape__Length
0,1,1,AK25,Walrus Islands State Game Sanctuary,State,AK,Zoned w/No Take Areas,Alaska Department of Fish and Game,Non-MPA Programmatic Species Management Plan,Natural Heritage,...,745.460999,99,0.000000,-160.231047,58.700885,2601,3.298504,0.117017,2.791294e+09,491586.303131
1,2,2,NPS10,Cape Hatteras National Seashore,Federal,NC,Uniform Multiple Use,National Park Service,Site-Specific Management Plan,Natural Heritage,...,28.920485,23,0.000000,-75.617180,35.242412,3797,2.741455,0.012495,1.901409e+08,343505.400043
2,3,3,AS1,Ofu Vaoto Marine Park,Territorial,ASM,No Take,American Samoa Department of Parks & Recreation,No Management Plan,Natural Heritage,...,0.384748,100,0.384755,-169.670240,-14.186982,51,0.025235,0.000032,4.093436e+05,2837.034473
3,4,4,CT1,Bluff Point State Park/Natural Area Preserve,State,CT,Zoned Multiple Use,Connecticut Department of Environmental Protec...,Site-Specific Management Plan,Natural Heritage,...,0.112254,4,0.000000,-72.030288,41.323971,547,0.156012,0.000321,5.292001e+06,19914.004750
4,5,5,CT10,Silver Sands State Park/Charles Island Natural...,State,CT,Zoned Multiple Use,Connecticut Department of Environmental Protec...,No Management Plan,Natural Heritage,...,0.014841,1,0.000000,-73.069498,41.202265,863,0.114932,0.000131,2.165473e+06,14112.522816

In [ ]:
shark_data.isnull()
#values are null wherever it says True

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22,Month,Season
0,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,False,False
1,False,False,False,False,False,False,False,False,False,True,...,True,True,True,True,True,True,True,True,False,False
2,False,False,False,False,False,False,False,True,False,False,...,True,True,True,True,True,True,True,True,False,False
3,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,True,True,True,True,False,False
4,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6964,True,True,True,True,True,True,True,True,True,True,...,True,False,True,True,True,True,True,True,False,False
6965,True,True,True,True,True,True,True,True,True,True,...,True,False,True,True,True,True,True,True,False,False
6966,True,True,True,True,True,True,True,True,True,True,...,True,False,True,True,True,True,True,True,False,False
6967,True,True,True,True,True,True,True,True,True,True,...,True,False,True,True,True,True,True,True,False,False
6968,True,True,True,True,True,True,True,True,True,True,...,True,False,True,True,True,True,True,True,False,False

In [ ]:
shark_data.isna().sum()

Date                25
Year               194
Type                43
Country             75
State              507
Location           590
Activity           611
Name               245
Sex                604
Age               3019
Injury              60
Unnamed: 11        587
Time              3551
Species           3157
Source              44
pdf                170
href formula       150
href               173
Case Number        171
Case Number.1      172
original order     170
Unnamed: 21       6968
Unnamed: 22       6967
Month                0
Season               0
dtype: int64

In [ ]:
shark_data.isna().sum(axis=1)

0        9
1       10
2        9
3        9
4        9
        ..
6964    22
6965    22
6966    22
6967    22
6968    22
Length: 6969, dtype: int64

In [ ]:
shark_data.dropna(thresh=6, inplace=True) # to delete rows with 5 or less empty values

In [ ]:
# drops all unwanted columns and saves the results to a series called shark_data_trimmed
drop_cols = ['pdf', 'href formula', 'href', 'Case Number', 'Case Number.1', 'Species ', 'original order', 'Unnamed: 21', 'Unnamed: 22', 'Source', 'Unnamed: 11', "Name"]
shark_data_trimmed = shark_data.drop( drop_cols, axis=1)

shark_data_trimmed

# Note: think about doing this step before the provoked and unprovoked variables so its based off the trimmed data

,Date,Year,Type,Country,State,Location,Activity,Sex,Age,Injury,Time,Month,Season
0,15-Mar-2024,2024,Unprovoked,AUSTRALIA,Queensland,Bargara Beach,Swimming,F,13,"Minor injuries to back, abdomen and legs",16h00,March,Spring
1,04-Mar-2024,2024,Unprovoked,USA,Hawaii,"Old Man's, Waikiki",Surfing,M,NaN,"No injury, shark bit surfboard",NaN,March,Spring
2,02-Mar-2024,2024,Unprovoked,USA,Hawaii,"Rainbows, Oahu",Swimming,F,11,Lacerations to left foot,13h30,March,Spring
3,25-Feb-2024,2024,Unprovoked,AUSTRALIA,Western Australia,"Sandlnd Island, Jurian Bay",NaN,F,46,Leg bitten,11h30,February,Winter
4,14-Feb-2024,2024,Unprovoked,INDIA,Maharashtra,"Vaitarna River, Palghar District",Fishing,M,32,Calf of lower left leg injured,NaN,February,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6939,1903,1903,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,M,NaN,FATAL,NaN,Unknown,Unknown
6940,1903,1903,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,M,NaN,FATAL,NaN,Unknown,Unknown
6941,1900-1905,1900,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,M,NaN,FATAL,NaN,Unknown,Unknown
6942,1883-1889,1883,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,M,NaN,FATAL,NaN,Unknown,Unknown
6943,1845-1853,1845,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,M,15,"FATAL. ""Shark bit him in half, carrying away t...",NaN,Unknown,Unknown

In [ ]:
#shark_data.dropna(axis=1) # idk why here

In [ ]:
usa_attack_data = shark_data_trimmed.groupby('Country').get_group('USA')
usa_attack_data

,Date,Year,Type,Country,State,Location,Activity,Sex,Age,Injury,Time,Month,Season
1,04-Mar-2024,2024,Unprovoked,USA,Hawaii,"Old Man's, Waikiki",Surfing,M,NaN,"No injury, shark bit surfboard",NaN,March,Spring
2,02-Mar-2024,2024,Unprovoked,USA,Hawaii,"Rainbows, Oahu",Swimming,F,11,Lacerations to left foot,13h30,March,Spring
10,30-Dec-2023,2023,Unprovoked,USA,Hawaii,"Baby Beach, Maui",Surfing,M,39,FATAL,11h12,December,Winter
24,05-Nov-2023,2023,Unprovoked,USA,Florida,"Juno Beach, Palm Beach County",Swimming,M,66,Lacerations to right forearm,10h30,November,Fall
29,25-Oct-2023,2023,Unprovoked,USA,Hawaii,"Pua’ena Point, Haleiwa, Oahu",Surfing,M,30,Bite to right thigh,15h05,October,Fall
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6891,1958,1958,Unprovoked,USA,Florida,"Palm Beach, Palm Beach County",Standing,M,NaN,Abrasions & bruises hip to ankle,NaN,Unknown,Unknown
6925,1921,1921,Unprovoked,USA,Florida,"Gadsden Point, Tampa Bay",Fishing,M,NaN,2-inch lacerations,NaN,Unknown,Unknown
6930,17-Jul-1916,1916,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,Swimming,M,NaN,"""Lost leg""",NaN,July,Summer
6934,Circa-1862,1862,Unprovoked,USA,Hawaii,Puna,NaN,F,NaN,Ankle bitten,NaN,Unknown,Unknown
6941,1900-1905,1900,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,M,NaN,FATAL,NaN,Unknown,Unknown

In [ ]:
# # replace all sentence and whitespace from the string date before handling to season
# shark_data['Date'] = shark_data['Date'].replace('Before ', '', regex=True)
# shark_data['Date'] = shark_data['Date'].replace(' ', '-', regex=True)
# # Extract all months ans year from the columns date
# shark_data['Month'] = shark_data['Date'].str.extract(r'([aA-Z]-z+)')
# shark_data['Year']= shark_data['Date'].str.extract(r'(\d{4})')
# # Create a Category for all months
# def map_month(month_abbr):
#     month_abbr_to_full = {
#         'Jan': 'January', 'Feb': 'February', 'Mar': 'March', 'Apr': 'April',
#         'May': 'May', 'Jun': 'June', 'Jul': 'July', 'Aug': 'August',
#         'Sep': 'September', 'Oct': 'October', 'Nov': 'November', 'Dec': 'December'
#     }
#     return month_abbr_to_full.get(month_abbr, 'Unknown')
# def get_season(month):
#     if month in ['December', 'January', 'February']:
#         return 'Winter'
#     elif month in ['March', 'April', 'May']:
#         return 'Spring'
#     elif month in ['June', 'July', 'August']:
#         return 'Summer'
#     elif month in ['September', 'October', 'November']:
#         return 'Fall'
#     else:
#         return 'Unknown'
# shark_data['Month'] = shark_data['Month'].apply(map_month)
# # Finish the category seasson for the months
# shark_data['Season'] = shark_data['Month'].apply(get_season)

In [ ]:
# # Creats a csv file and saves the data to it
# usa_attack_data.to_csv('USA_Shark.csv', index=False)

# # Code to download it to your system
# #from google.colab import files
# #files.download('USA_Shark.csv')

In [ ]:
# makes a series variable of data for provoked attacks
provoked_data = usa_attack_data[usa_attack_data['Type'] == 'Provoked']
provoked_data_unique = provoked_data.drop_duplicates(subset=['Activity'], keep='first')
provoked_data

,Date,Year,Type,Country,State,Location,Activity,Sex,Age,Injury,Time,Month,Season
80,19--May-2023,2023,Provoked,USA,Florida,"Flagship Drive, Summerland Key, Monroe County",Fishing,M,35,PROVOKED INCIDENT Hooked shark bit his foot,20h00,May,Spring
85,11-May-2023,2023,Provoked,USA,Hawaii,"Kualoa, Oahu",Kayak fishing,M,NaN,"Shark bit kayak, no inury to occupant",NaN,May,Spring
116,01-Jan-2023,2023,Provoked,USA,Florida,70 miles off Pensacola,Spearishing,M,30,Knocked spear out of his hands and fin bitten,14h50,January,Winter
126,03-Nov-2022,2022,Provoked,USA,Florida,"Cape San Blas, Gulf County",Fishing,M,29,Right knee & thigh bitten by hooked shark,15h30,November,Fall
130,27-Oct-2022,2022,Provoked,USA,Mississippi,Horn Island,Fishing,M,NaN,Minor injuries,NaN,October,Fall
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6524,28-Jul-1873,1873,Provoked,USA,Maryland,Chester River,Fishing (Seining),M,NaN,Leg severely bitten by netted shark. Lower leg...,NaN,July,Summer
6538,Aug-1871,1871,Provoked,USA,New York,Long Island,Shark fishing,M,NaN,Hand injured PROVOKED INCIDENT,NaN,August,Summer
6588,Reported-09-Jul-1863,1863,Provoked,USA,Hawaii,Palama,Fishing,M,NaN,Hand severed by noosed shark PROVOKED INCIDENT,NaN,Unknown,Unknown
6696,06-Jul-1842,1842,Provoked,USA,New Jersey,"Absecon, Atlantic County",Harassing a shark,NaN,NaN,Lacerations to leg PROVOKED INCIDENT,NaN,July,Summer
6868,"No-date,--1975",1975,Provoked,USA,Florida,"Riviera Beach, Palm Beach County",Skin diving. Grabbed shark's tail; shark turne...,M,19,"Ankle punctured & lacerated, hands abraded PRO...",NaN,Unknown,Unknown

In [ ]:
# makes a series variable of data for unprovoked attacks
non_provoked_data = usa_attack_data[usa_attack_data['Type'] != 'Provoked']
non_provoked_data

,Date,Year,Type,Country,State,Location,Activity,Sex,Age,Injury,Time,Month,Season
1,04-Mar-2024,2024,Unprovoked,USA,Hawaii,"Old Man's, Waikiki",Surfing,M,NaN,"No injury, shark bit surfboard",NaN,March,Spring
2,02-Mar-2024,2024,Unprovoked,USA,Hawaii,"Rainbows, Oahu",Swimming,F,11,Lacerations to left foot,13h30,March,Spring
10,30-Dec-2023,2023,Unprovoked,USA,Hawaii,"Baby Beach, Maui",Surfing,M,39,FATAL,11h12,December,Winter
24,05-Nov-2023,2023,Unprovoked,USA,Florida,"Juno Beach, Palm Beach County",Swimming,M,66,Lacerations to right forearm,10h30,November,Fall
29,25-Oct-2023,2023,Unprovoked,USA,Hawaii,"Pua’ena Point, Haleiwa, Oahu",Surfing,M,30,Bite to right thigh,15h05,October,Fall
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6891,1958,1958,Unprovoked,USA,Florida,"Palm Beach, Palm Beach County",Standing,M,NaN,Abrasions & bruises hip to ankle,NaN,Unknown,Unknown
6925,1921,1921,Unprovoked,USA,Florida,"Gadsden Point, Tampa Bay",Fishing,M,NaN,2-inch lacerations,NaN,Unknown,Unknown
6930,17-Jul-1916,1916,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,Swimming,M,NaN,"""Lost leg""",NaN,July,Summer
6934,Circa-1862,1862,Unprovoked,USA,Hawaii,Puna,NaN,F,NaN,Ankle bitten,NaN,Unknown,Unknown
6941,1900-1905,1900,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,M,NaN,FATAL,NaN,Unknown,Unknown

In [ ]:
non_provoked_data.head().groupby(['Date','State', 'Location'])['Year'].mean()

Date         State    Location
02-Mar-2024  Hawaii   Rainbows, Oahu                   2024.0
04-Mar-2024  Hawaii   Old Man's, Waikiki               2024.0
05-Nov-2023  Florida  Juno Beach, Palm Beach County    2023.0
25-Oct-2023  Hawaii   Pua’ena Point,  Haleiwa, Oahu    2023.0
30-Dec-2023  Hawaii   Baby Beach, Maui                 2023.0
Name: Year, dtype: object

In [ ]:
non_provoked_data.isna().sum()

Date          0
Year         27
Type          8
Country       0
State         5
Location     48
Activity    146
Sex          88
Age         694
Injury        6
Time        769
Month         0
Season        0
dtype: int64

In [ ]:
non_pro_pivot = non_provoked_data.pivot_table(index='State', columns='Month' , values=['Season'], aggfunc='sum')

pd.set_option('display.max_columns', None) # shows all columns
non_pro_pivot.head()

                 Season                                          \
Month             April        August December February January
State
 New Jersey         NaN           NaN      NaN      NaN     NaN
 North Carolina     NaN        Summer      NaN      NaN     NaN
Alabama          Spring  SummerSummer      NaN      NaN     NaN
Bahamas             NaN           NaN      NaN      NaN     NaN
CUBA                NaN        Summer      NaN      NaN     NaN

                                                                           \
Month                                July                      June March
State
 New Jersey                           NaN                       NaN   NaN
 North Carolina                       NaN                       NaN   NaN
Alabama          SummerSummerSummerSummer  SummerSummerSummerSummer   NaN
Bahamas                            Summer                       NaN   NaN
CUBA                                  NaN                       NaN   NaN


Month            May November October September                Unknown
State
 New Jersey      NaN      NaN     NaN       NaN                Unknown
 North Carolina  NaN      NaN     NaN       NaN                    NaN
Alabama          NaN      NaN    Fall      Fall  UnknownUnknownUnknown
Bahamas          NaN      NaN     NaN       NaN                    NaN
CUBA             NaN      NaN     NaN       NaN                    NaN

In [ ]:
shark_data

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Unnamed: 11,Time,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22,Month,Season
0,15-Mar-2024,2024,Unprovoked,AUSTRALIA,Queensland,Bargara Beach,Swimming,Brooklyn Sauer,F,13,"Minor injuries to back, abdomen and legs",NaN,16h00,Tiger shark,"Yahoo News, 3/15/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,March,Spring
1,04-Mar-2024,2024,Unprovoked,USA,Hawaii,"Old Man's, Waikiki",Surfing,Matthew White,M,NaN,"No injury, shark bit surfboard",N,NaN,Tiger shark 8',"Surfer, 3/6/2024F",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,March,Spring
2,02-Mar-2024,2024,Unprovoked,USA,Hawaii,"Rainbows, Oahu",Swimming,NaN,F,11,Lacerations to left foot,N,13h30,3' to 4' shark,"Hawaii News Now, 3/4/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,March,Spring
3,25-Feb-2024,2024,Unprovoked,AUSTRALIA,Western Australia,"Sandlnd Island, Jurian Bay",NaN,female,F,46,Leg bitten,N,11h30,Tiger shark,"WA Today, 2/26/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,February,Winter
4,14-Feb-2024,2024,Unprovoked,INDIA,Maharashtra,"Vaitarna River, Palghar District",Fishing,Vicky Suresh Govari,M,32,Calf of lower left leg injured,N,NaN,"Bull shark, 7'","Times of India, 2/14/2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,February,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6939,1903,1903,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN,Unknown,Unknown
6940,1903,1903,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,Unknown,Unknown
6941,1900-1905,1900,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,Unknown,Unknown
6942,1883-1889,1883,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,Unknown,Unknown
6943,1845-1853,1845,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,Unknown,Unknown

In [ ]:
us_attacks = non_provoked_data[non_provoked_data['Country'] == 'USA']

In [ ]:
attacks_by_season = us_attacks.groupby('Season').size()
print("Total amount of unprovoked Shark Attacks by Seasons: ")
print(attacks_by_season)

Total amount of unprovoked Shark Attacks by Seasons:
Season
Fall       621
Spring     419
Summer     907
Unknown    181
Winter     177
dtype: int64

In [ ]:
provoked_data['Age'] = pd.to_numeric(shark_data['Age'], errors='coerce')

<ipython-input-24-57a6f08fe837>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  provoked_data['Age'] = pd.to_numeric(shark_data['Age'], errors='coerce')

In [ ]:
provoked_age = provoked_data.groupby("Sex")['Age'].mean()
provoked_age

Sex
F    30.181818
M    30.648148
Name: Age, dtype: float64

In [ ]:
provoked_age = provoked_data.groupby("Sex")['Age'].median()
provoked_age

Sex
F    32.0
M    29.0
Name: Age, dtype: float64